name: GitHub Action Demo
on: 
  [workflow_dispatch]:
    inputs:
      server:
        description: 'Environment to deploy'
        required: true
        default: 'dev'
jobs:
  get-source:
    runs-on: ubuntu-latest
    steps: 
      - name: Start Workflow
        run: echo "Workflow démarré"
